# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e51c8b9013fee4552943aea0b49218d9f950adbe48404aa09bb7751b1ed9d230401c2e2e6c610e8b2e0f8ba43bdc7c9b8cd5e7b9bbd6038792672e762b4653

test:
  secret_key_base: 47e4e970ea49c84a0e7f6995ae42cf8cd55ccccd41634b0d73180ea8418487c42962f7a54b6766a56f56710b850e563ca4b2ebe988efde84af34af201f73795a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
